-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Mar 16, 2019 at 05:22 AM
-- Server version: 5.7.19
-- PHP Version: 7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `csv_db`
--
CREATE DATABASE IF NOT EXISTS `dogmanagement` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `dogmanagement`;

-- --------------------------------------------------------

--
-- Table structure for table `doginfo`
--

DROP TABLE IF EXISTS `doginfo`;
CREATE TABLE IF NOT EXISTS `doginfo` (
  `id` int(8) NOT NULL,
  `name` varchar(20) NOT NULL,
  `age` varchar(5) NOT NULL,
  `breed` varchar(30) NOT NULL,
  `size` varchar(3) NOT NULL,
  `sex` varchar(4) NOT NULL,
  `status` varchar(6) NOT NULL,
  `altered` varchar(7) NULL,
  `hasShots` varchar(8) NULL,
  `houseTrained` varchar(12) DEFAULT NULL,
  `dateAdded` date DEFAULT NULL,
  `description` varchar(20000),
  `pic1` varchar(100) NULL,
  `pic2` varchar(100) NULL,
  Primary KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `doginfo`
--

INSERT INTO `doginfo` (`id`, `name`, `age`, `breed`, `size`, `sex`, `status`, `altered`, `hasShots`, `houseTrained`,`dateAdded` ,`description`, `pic1`, `pic2`) VALUES
(43391433, 'JamieLynn', 'Young', 'Mixed Breed', 'M', 'F', 'A', 'yes', 'yes', 'yes', '2019/01/09', 'Name: JamieLynn Breed: Mutt mix Approximate Age: 1 year Approximate Weight: 50 lbs Sex: Female Hi there! I\'m JamieLynn! My foster parents say I am a sweet, smart girl. I really like to be near my people and I LOVE to be petted and belly rubs!! I am a strong girl working on my leash manners. I am learning fast, I would love a family that would take me to training, I already know \"sit\" ,âdownâ, and âcrateâ (I go right in when Iâm told) and would love to learn more! I like to run and prance around in the yard. My favorite place to be is snuggled up on the couch! Iâve been in New England searching for my forever family for a while now. I hope to find my forever home soon! Compatibility: Dogs: Yes, with proper intros Cats: Unknown Kids: Yes, has been around 13+ year olds The Basics: House Broken: Yes Crate Trained: Yes', 'http://photos.petfinder.com/photos/pets/43391433/1/?bust=1543337135&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43391433/2/?bust=1543337139&width=300&-pn.jpg'),
(43674141, 'Rambo', 'Adult', 'Shepherd', 'L', 'M', 'A', 'yes', 'yes', 'yes', '2019/03/01', 'Name: Rambo Breed: Shepherd mix Approximate Age: 5 years Approximate Weight: 70 lbs Sex: Male Rambo, I just love that name. It is a strong name that conjures up survival of the fittest. I am a survivor. I survived an awful beginning to my life. I wish I could tell you about it. I do have a scar on my back leg from a wire wrapped around it to keep me from running away. My survival kicked in and now I have a white ring around my ankle as a reminder. I call it my ankle bracelet. Then I was dumped at a strangerâs house. This stranger took me in and was able to find me a loving foster mom who took great care of me. Even when I was diagnosed with heart worms she took care of me through the whole treatment. Once again I survived and thought I had found my forever home. I didnât understand why she was sending me away. She kept telling me how much she loves me and New England is where I belong. So now Iâm going into Rambo mode again and dealing with this dreadful weather yâall have up here. All Iâm looking for is someone to love me forever. Iâm looking for someone to hang out with and love on me and feed me and take me for walks and not leave me alone for long periods of time. I love to play with other dogs. Mostly the ones smaller than me but I love the most being with people. Are you willing to share your bed with me? Are you a hugger and a kisser because those are my favorite things? Compatibility: Dogs: Yes Cats: Yes Kids: Unknown The Basics: House broken: Yes Crate trained: Yes, it is not my favorite but I tolerate it if I must', 'http://photos.petfinder.com/photos/pets/43674141/1/?bust=1551718235&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43674141/2/?bust=1551718236&width=300&-pn.jpg'),
(43674230, 'Tony', 'Adult', 'Labrador Retriever', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/01/12', 'Name: Tony Breed: Lab mix Approximate Age: 2 years Approximate Weight: 42 lbs Sex: Male I was returned to the rescue because Iâm timid when meeting strangers and I didn\'t get the training to help me get better so I just got more fearful. Since coming back I spent some time with an awesome trainer who taught me all sorts of things and helped me get better when meeting people and now Iâm ready to find my perfect forever family! I know lots of fun things like âsitâ, âplaceâ and âkennelâ. I like to take my time getting to know you (I am not a kiss on the first date kind of guy), so I want a family who wonât rush me and will respect my space. Once I get to know you, all I want is to snuggle up and get love and attention. My foster mom says Iâm like Velcro because I always want to be right with her (but itâs okay because I give great cuddles). Hopefully I find my family soon... how can you resist this underbite?! Compatibility: Dogs: Yes Cats: Yes Kids: Older kids (12+) The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/43674230/1/?bust=1546450153&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43674230/2/?bust=1546450157&width=300&-pn.jpg'),
(43762912, 'Buck', 'Young', 'Chihuahua', 'S', 'M', 'A', 'yes', 'yes', 'yes', '2019/01/22', 'Name: Buck Breed: Chihuahua mix Approximate Age: 1.5 years Approximate Weight: 18 lbs Sex: Male I am a sweet guy and I just love everyone and everything I meet! My favorite thing to do is lounge on the couch with my humans. I get along well with my K9 friends and like to run around and play with them out in the yard. I would make a great addition to any family! Compatibility: Dogs: Yes Cats: Yes Kids: Yes The Basics: House broken: Mostly Crate trained: Working on it', 'http://photos.petfinder.com/photos/pets/43762912/1/?bust=1551369037&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43762912/2/?bust=1547394739&width=300&-pn.jpg'),
(43762944, 'Spike', 'Young', 'Mixed Breed', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/02/21', 'Name: Spike Breed: Mutt Approximate Age: 1 year Approximate Weight: 54 lbs Sex: Male Hi New England, I am so happy to be here!! I was left abandoned by my owners with a nice elderly couple in Texas, they had agreed to watch me for a short time and then no one came back for me and I had no place to go because I am too young and energetic for the nice people that tried to help. Luckily the nice rescue lady said she could help me and took me so now here I am and I\'m trying to find a loving forever home. I get along well with all of my K9 friends but tend to bark a lot when I see them but I\'m just trying to get their attention because I want to play. I had a nice foster brother and sister who were teaching me a lot! I also had a foster kitty sister but I\'m a little afraid of her. I even got to experience that white stuff you call snow and it\'s fun!!! I love to snuggle and will do most anything for belly rubs! I cannot wait to find a family that will love me forever! Compatibility: Dogs: Yes, with proper introductions Cats: Yes Kids: Yes, has been with 13+ year olds The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/43762944/1/?bust=1547395111&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43762944/2/?bust=1550437958&width=300&-pn.jpg'),
(43943559, 'Remington', 'Adult', 'Treeing Walker Coonhound', 'XL', 'M', 'A', 'yes', 'yes', 'yes', '2019/01/14', 'Name: Remington Breed: Walker Hound mix Approximate Age: 4 years Approximate Weight: 100 lbs Sex: Male I am looking for a loving family that will help me get my summer bod in shape...they say I am a bit overweight, I can\'t help it if I like to eat! I really do love food, so sometimes I try to sneak up to check the counters, but when you tell me \"no\" I listen. I am really friendly and love people, so I want my forever family to give me lots of love and attention (plus take me on walks)! I am so excited to find my perfect family! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/43943559/1/?bust=1549378468&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43943559/2/?bust=1550437852&width=300&-pn.jpg'),
(43943581, 'Bubba', 'Adult', 'Shar-Pei', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/02/11', 'Name: Bubba Breed: Shar Pei mix Approximate Age: 3 years Approximate Weight: 45 lbs Sex: Male I am a goofy, happy boy and I cannot wait to find my forever family! I always have a smile on my face and will surely put a smile on yours each day. I am a high energy boy so I am looking for an active family that will take me on fun adventures and teach me new things! I am very excited to be moving to New England soon and I hope you will be waiting for me! Compatibility: Dogs: Yes Cats: No Kids: Yes, has been with 13+ year olds The Basics: House broken: Mostly Crate trained: In Progress', 'http://photos.petfinder.com/photos/pets/43943581/3/?bust=1550437533&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43943581/4/?bust=1550437533&width=300&-pn.jpg'),
(43943589, 'Koda', 'Adult', 'Beagle', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/03/13', 'Name: Koda Breed: Beagle mix Approximate Age: 1.5 years Approximate Weight: 35 lbs Sex: Male I am a friendly boy and I love attention. I don\'t have the typical beagle traits so I am probably not a true beagle at heart but thats what my paperwork says so we will go with it. I play well with my K9 friends and am more of a submissive boy. I am a smart boy and would love a family that will take me to doggy school so I can learn fun commands and tricks! I would love an active family that will play with me and take me on fun adventures, I will repay you with lots of kisses! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/43943589/1/?bust=1549378723&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43943589/2/?bust=1549378728&width=300&-pn.jpg'),
(43990605, 'Cooper', 'Adult', 'Pointer', 'L', 'M', 'A', 'yes', 'yes', 'yes', '2019/02/18', 'Name: Cooper Breed: Pointer mix Approximate Age: 2 years Approximate Weight: 80 lbs Sex: Male I was adopted about a year and a half ago as a young pup and my family just told me I have to move out because they no longer have time for me...I am so confused, I am a good boy I promise! I have gone to doggy school and know lots of fun tricks, I am still working on my leash manners but I am smart and will catch on. I am still young so I do have a pretty good amount of energy so I would love to find an active family! Compatibility: Dogs: Yes Cats: Likes to chase them Kids: Older The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/43990605/1/?bust=1549893419&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43990605/2/?bust=1551718377&width=300&-pn.jpg'),
(44015695, 'Eylua', 'Adult', 'Catahoula Leopard Dog', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/2/12', 'Name: Eylua Breed: Catahoula mix Approximate Age: 2.5 years Approximate Weight: 64 lbs Sex: Male I am a sweet, active boy and I would love to find an active family that will take me on fun adventures and teach me new things! I am a smart boy and am working on learning some basic commands but would love to learn more. I am very excited to be here in New England and I hope my forever family will adopt me soon. Compatibility: Dogs: Yes Cats: Unknown Kids: Has been around 13+ year olds The Basics: House broken: Mostly Crate trained: In progress', 'http://photos.petfinder.com/photos/pets/44015695/1/?bust=1550176613&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44015695/2/?bust=1550176620&width=300&-pn.jpg'),
(44047979, 'Casper', 'Adult', 'American Bulldog', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/3/12', 'Name: Casper Breed: Bully mix Approximate Age: 5 years Approximate Weight: 58 lbs Sex: Male I am a sweet boy and very submissive to my humans. I like to play with my female K9 friends but can be selective with my male friends. I am excited to be moving to New England soon and hope my forever family is waiting for me! Compatibility: Dogs: Yes, selective: Prefers dogs smaller than him. Needs proper introductions. Cats: Yes Kids: Yes, has been with 13+ year olds The Basics: House broken: Mostly Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44047979/1/?bust=1550541292&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44047979/2/?bust=1550541304&width=300&-pn.jpg'),
(44048153, 'Baretta', 'Adult', 'Mixed Breed', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/2/12', 'Name: Baretta Breed: Mutt Approximate Age: 2 years Approximate Weight: 49 lbs Sex: Male I am a sweet boy and I get along well with all of my K9 friends. I heard I am moving to New England soon and will get to find a family to love me forever! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Unknown Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44048153/1/?bust=1550541728&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44048153/2/?bust=1550541678&width=300&-pn.jpg'),
(44048479, 'Joe', 'Adult', 'Terrier', 'S', 'M', 'A', 'yes', 'yes', 'yes', '2019/2/16', 'Donât forget to come meet Joe tomorrow 11am-1pm at the Cumberland PetValu Adoption Event!! Name: Joe Breed: Terrier mix Approximate Age: 5 years Approximate Weight: 15 lbs Sex: Male I am a sweet and happy guy once I get to know you. I can be a little shy and \"nippy\" at first but just need some time and space and I come around quickly. I like my crate so much I do not like any other dogs in it, that is MY personal space. I love to play with my toys and K9 friends. I am very excited to be here in New England and to start my search for a family who is just waiting to love me forever! Compatibility: Dogs: Yes Cats: Unknown Kids: Older since I can be nippy with strangers The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44048479/1/?bust=1551717906&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44048479/2/?bust=1551717991&width=300&-pn.jpg'),
(44069466, 'Dex', 'Baby', 'Shepherd', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/2/25', 'Name: Dex Breed: Shepherd mix Approximate Age: 6 months Approximate Weight: 30 lbs Sex: Male Special Requirements: Will only be adopted to a family with another dog I am a timid guy and am scared in new situations and when I meet new people. It can take me a little bit to warm up since I did not have much human interaction my first few months. I may bark or growl at people when I meet them the first few times. If you are patient, I will warm up to you! I am looking for a patient family that is willing to put in the work - I promise I will be worth it! I am looking for a home with another active K9 brother/sister who can show me the ropes. I may be timid with people, but I show my true colors around my K9 friends and I have some serious energy to burn! Compatibility: Dogs: Yes Cats: Unknown Kids: Older, is too scared to be around young children right now The Basics: House broken: In Progress Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44069466/1/?bust=1550777979&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44069466/2/?bust=1550778193&width=300&-pn.jpg'),
(44078383, 'Randi', 'Adult', 'Mixed Breed', 'L', 'M', 'A', 'yes', 'yes', 'yes', '2019/2/17', 'Name: Randi Breed: Mutt Approximate Age: 8 years Approximate Weight: 71 lbs Sex: Male I am a sweet, older Southern gentleman looking for a family to love me through my golden years! I get along well with all of my K9 friends big and small. I need to lose a few pounds and I hope I get to run around in that white fluffy stuff all my friends keep telling me about! I am very excited to be making my way to New England and I hope my forever family is waiting to meet me! Compatibility: Dogs: Yes Cats: Yes Kids: Yes The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44078383/1/?bust=1551718088&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44078383/3/?bust=1551382130&width=300&-pn.jpg'),
(44078390, 'Tinsel', 'Young', 'Boxer', 'M', 'F', 'A', 'yes', 'yes', 'yes', '2019/2/18', 'Name: Tinsel Breed: Boxer mix Approximate Age: 1.5 years Approximate Weight: 42 lbs Sex: Female Are you looking for a sweet, lovable, playful best buddy? If you are look no further, here I am. I am the sweetest girl and I love all the people I meet. I love lots of attention, cuddles, and toys. I know how to sit and would love to learn more tricks. I really love my crate and don\'t mind sleeping in there. I am working on gaining weight because I am a parvo survivor. I love to eat and I\'m not very picky so my weight should be up in no time. My foster mom says I\'m pretty chill in the house and just want to be wherever my humans are. Looking forward to finding my furever home! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes, has been with 13+ year olds The Basics: House broken: Yes Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44078390/1/?bust=1550887666&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44078390/2/?bust=1550887677&width=300&-pn.jpg'),
(44117389, 'Chancie', 'Adult', 'American Bulldog', 'M', 'F', 'A', 'yes', 'yes', 'no', '2019/3/11', 'Name: Chancie Breed: Bully mix Approximate Age: 2 years Approximate Weight: 42 lbs Sex: Female I showed up on a farm in Texas, skinny, hungry. and BB gun pellets under my skin...the nice little girls took care of me for a little while but no one came looking for me so they called the nice rescue lady to come help find me a new home. I get along well with all of my K9 friends and am a very sweet girl. I am excited to be moving to New England and leaving my past behind! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Unknown Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44117389/1/?bust=1551315760&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44117389/2/?bust=1551315774&width=300&-pn.jpg'),
(44151255, 'Tuff', 'Young', 'Mixed Breed', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/2/10', 'Name: Tuff Breed: Mutt Approximate Age: 1 year Approximate Weight: 38 lbs Sex: Male I am a friendly and energetic boy...I love to play with all of my K9 friends. I would love to find an active family that will take me on fun adventures and teach me new things. I hear I am moving to New England soon and I hope you will be waiting for me! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes, has been with 13+ year olds The Basics: House broken: Unknown Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44151255/1/?bust=1551721241&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44151255/2/?bust=1551721253&width=300&-pn.jpg'),
(44151272, 'Red', 'Adult', 'Labrador Retriever', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/2/15', 'Name: Red Breed: Lab mix Approximate Age: 2 years Approximate Weight: 56 lbs Sex: Male I am a sweet boy and I get along well with all of my K9 friends. I was a blood donor when I was at the shelter and helped save other dog\'s lives, I am kind of a big deal ya know! I am very excited to be moving to New England soon and I hope my forever family will be waiting to meet me when I arrive! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Unknown Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44151272/1/?bust=1551721479&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44151272/2/?bust=1551721482&width=300&-pn.jpg'),
(44166404, 'Jake', 'Adult', 'Labrador Retriever', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/2/19', 'Name: Jake Breed: Lab mix Approximate Age: 4 years Approximate Weight: 56 lbs Sex: Male I am a very friendly guy and I am very excited to be moving to New England soon so I can find my forever family! I get along with my K9 friends of all sizes. I am a typical lab and love food! I am very food motivated and smart so training will be fun with me; I have already learned \"sit\"! I hope you will be waiting for me when I arrive! Compatibility: Dogs: Yes Cats: No Kids: Yes, has been with 13+ year olds The Basics: House broken: Yes Crate trained: Mostly', 'http://photos.petfinder.com/photos/pets/44166404/1/?bust=1551897960&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44166404/2/?bust=1551897964&width=300&-pn.jpg'),
(44166459, 'Neo', 'Adult', 'Hound', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/2/4', 'Name: Neo Breed: Hound mix Approximate Age: 5 years Approximate Weight: 34 lbs Sex: Male I am a very friendly guy and I never meet a stranger. I love to play with my K9 friends and my toys. I love to go for rides in the car and see the big world. My favorite pastime is chasing squirrels, you don\'t have to worry about them taking over your yard with me around! I am very excited to be moving to New England and hope my forever family is waiting for me! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: Yes & doggy door Crate trained: Yes', 'http://photos.petfinder.com/photos/pets/44166459/1/?bust=1551898052&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44166459/2/?bust=1551898054&width=300&-pn.jpg'),
(44180402, 'Lamar', 'Baby', 'Beagle', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/2/1', 'Name: Lamar Breed: Beagle/Basset Hound mix Approximate Age: 4 months Approximate Weight: 24 lbs Sex: Male I am a fun loving pup looking for my forever home to grow up in! I love to play with my K9 friends and my toys. I am very excited to be moving to New England so I can find my forever family! Compatibility: Dogs: Yes Cats: Unknown Kids: Yes The Basics: House broken: In progress Crate trained: In progress', 'http://photos.petfinder.com/photos/pets/44180402/1/?bust=1552009978&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44180402/2/?bust=1552010185&width=300&-pn.jpg'),
(38280604, 'Jaiden', 'Young', 'Pit Bull Terrier', 'L', 'F', 'A', 'yes', 'yes', 'yes', '2019/2/3', 'When the behavior team tells me that Jaiden is âa breath of fresh airâ, I need to take notice! They love her and with good reason. Sheâs a rock star in play group, a âgentle and daintyâ player, greets other dogs politely, and corrects appropriately if needed. Sheâs so good they told me sheâs the next âsocial greeterâ for group play. Sheâs a gorgeous little girl, her tan coat shows care, and her preferred âhair styleâ is one ear up at attention, and the other down â so cute! Jaidenâs former owner left her with a friend and never came back for her, and the friend couldnât keep her long term. Let his loss be your gain, as sheâs a terrific little girl. She loved playing with toys and doesnât guard them, loved chasing a ball and then carried it with her for part of our walk! Her tail wags as we walk, she greets other dogs we pass with an easy tail wave and sheâs simply a joy to spend time with. Sheâs as good a cuddler as she is ball player, coming in my lap for some kisses and petting. Sheâs a lively little girl who loves everyone and everything, and the only thing missing in her life right now is that one special person or family to love. Meet our Jaiden today and be prepared to take our âbreath of fresh airâ home with you. Yes, sheâs that sweet. LOVES dogs and LOVES kids!!!!', 'http://photos.petfinder.com/photos/pets/38280604/1/?bust=1496801954&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/38280604/2/?bust=1496801955&width=300&-pn.jpg'),
(38280605, 'Rusty', 'Adult', 'Dachshund', 'M', 'M', 'A', 'no', 'yes', 'yes', '2019/3/14', 'Rusty is a SUPER DOG!!! Rusty was saved by Odies Place this past July and is a downed dog. He became paralyzed this past June and was surrendered to Manhattan ACC because of it. There he was saved by Odies Place. He has awesome new wheels and is a giant lovebug. Great with dogs likes to chase cats even with 2 legs this boy can get around . Rusty is a special needs dog who will need to go to a family with experience with a downed dog. Those looking to learn more about Rusty\'s story here it is http://www.odiesplace.org/blog/2016/7/19/rusty-strong-rustys-redemption 3/3/19 11:15 AM', 'http://photos.petfinder.com/photos/pets/38280605/1/?bust=1496801957&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/38280605/2/?bust=1496801957&width=300&-pn.jpg'),
(40173598, 'Sasha', 'Young', 'Chihuahua', 'S', 'F', 'A', 'yes', 'yes', 'no', '2019/3/15', 'The coolest puppy around is here!!! Meet Sasha Fierce!!!! 8 month old 8.8 pound bundle of joy!!! We prefer she be in a fenced in yard due to previously being a stray .', 'http://photos.petfinder.com/photos/pets/40173598/1/?bust=1527108886&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/40173598/2/?bust=1527108886&width=300&-pn.jpg'),
(43459210, 'Midnight', 'Baby', 'Tuxedo', 'M', 'M', 'A', 'no', 'yes', 'yes', '2019/3/16', 'Midnight along with his brother Eclipse were rescued from living in a back yard . They are around 6 months old and are such cuddle bugs!!', 'http://photos.petfinder.com/photos/pets/43459210/1/?bust=1543983192&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43459210/2/?bust=1548303711&width=300&-pn.jpg'),
(43459225, 'Eclipse', 'Young', 'Tuxedo', 'M', 'M', 'A', 'yes', 'yes', 'no', '2019/3/17', 'Midnight along with his brother Eclipse were rescued from living in a back yard . They are around 6 months old and are such cuddle bugs!!', 'http://photos.petfinder.com/photos/pets/43459225/1/?bust=1543983368&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/43459225/2/?bust=1548303629&width=300&-pn.jpg'),
(44134702, 'Midnight', 'Young', 'Tuxedo', 'M', 'M', 'A', 'yes', 'no', 'no', '2019/3/21', 'Midnight along with his brother Eclipse were rescued from living in a back yard . They are around 6 months old and are such cuddle bugs!!', 'http://photos.petfinder.com/photos/pets/44134702/1/?bust=1551701654&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44134702/2/?bust=1551641953&width=300&-pn.jpg'),
(44134703, 'Eclipse', 'Young', 'Tuxedo', 'M', 'M', 'A', 'yes', 'no', 'yes', '2019/3/22', 'Midnight along with his brother Eclipse were rescued from living in a back yard . They are around 6 months old and are such cuddle bugs!!', 'http://photos.petfinder.com/photos/pets/44134703/1/?bust=1551701654&width=300&-pn.jpg', ''),
(44134704, 'Bruce Wayne', 'Young', 'Shepherd', 'M', 'M', 'A', 'yes', 'yes', 'yes', '2019/3/20', 'Bruce Wayne was rescued off the Memphis Animal Shelter\'s urgent list on 2/27/19 and is a shepard lab mix who is a little over 1 years old. Shy around dogs loves people!!! Prefers to be with someone all the time doesn\'t like to be left alone for long period of time. He will be arriving in Massachusetts around 3/16/19', 'http://photos.petfinder.com/photos/pets/44134704/1/?bust=1551544967&width=300&-pn.jpg', 'http://photos.petfinder.com/photos/pets/44134704/2/?bust=1551544970&width=300&-pn.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
